version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sector_db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_pass
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sector_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    restart: unless-stopped
volumes:
  postgres-data:
